name = "HamiltonianFlows"
uuid = "5fb78580-10a0-4606-82bc-07a60f425ab3"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "1.0.2"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
CTBase = "0.4"
OrdinaryDiffEq = "6.44"
julia = "1.8"
